In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('/Users/muhammadnehal/Desktop/mindlens/datasets/text/depression_dataset_reddit_cleaned.csv')

In [4]:
df1.head()

                                          clean_text  is_depression
0  we understand that most people who reply immed...              1
1  welcome to r depression s check in post a plac...              1
2  anyone else instead of sleeping more when depr...              1
3  i ve kind of stuffed around a lot in my life d...              1
4  sleep is my greatest and most comforting escap...              1

In [5]:
df1.shape

(7731, 2)

In [6]:
df1.tail()

                                             clean_text  is_depression
7726                                       is that snow              0
7727                 moulin rouge mad me cry once again              0
7728  trying to shout but can t find people on the list              0
7729  ughh can t find my red sox hat got ta wear thi...              0
7730  slept wonderfully finally tried swatching for ...              0

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7731 entries, 0 to 7730
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   clean_text     7731 non-null   str
 1   is_depression  7731 non-null   int64
dtypes: int64(1), str(1)
memory usage: 120.9 KB

In [8]:
df1.isnull().sum()

clean_text       0
is_depression    0
dtype: int64

In [9]:
df2 = pd.read_csv('/Users/muhammadnehal/Desktop/mindlens/datasets/text/Suicide_Detection.csv')

In [10]:
df2.head()

   Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [11]:
df2.shape

(232074, 3)

In [12]:
print(df1.columns)
print(df2.columns)

Index(['clean_text', 'is_depression'], dtype='str')
Index(['Unnamed: 0', 'text', 'class'], dtype='str')

In [13]:
df2.drop(columns=['Unnamed: 0'], inplace=True)

In [14]:
df2.head()

                                                text        class
0  Ex Wife Threatening SuicideRecently I left my ...      suicide
1  Am I weird I don't get affected by compliments...  non-suicide
2  Finally 2020 is almost over... So I can never ...  non-suicide
3          i need helpjust help me im crying so hard      suicide
4  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [15]:
print(df2.columns)

Index(['text', 'class'], dtype='str')

In [16]:
df1 = df1.rename(columns={"clean_text":"text"})
df1 = df1.rename(columns={"is_depression":"target"})
df2 = df2.rename(columns={"class":"target"})

In [17]:
df1.head()

                                                text  target
0  we understand that most people who reply immed...       1
1  welcome to r depression s check in post a plac...       1
2  anyone else instead of sleeping more when depr...       1
3  i ve kind of stuffed around a lot in my life d...       1
4  sleep is my greatest and most comforting escap...       1

In [18]:
df2.head()

                                                text       target
0  Ex Wife Threatening SuicideRecently I left my ...      suicide
1  Am I weird I don't get affected by compliments...  non-suicide
2  Finally 2020 is almost over... So I can never ...  non-suicide
3          i need helpjust help me im crying so hard      suicide
4  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [19]:
df2["target"] = df2["target"].map({
    "suicide":1,
    "non-suicide":0
})

In [20]:
df2.head()

                                                text  target
0  Ex Wife Threatening SuicideRecently I left my ...       1
1  Am I weird I don't get affected by compliments...       0
2  Finally 2020 is almost over... So I can never ...       0
3          i need helpjust help me im crying so hard       1
4  I’m so lostHello, my name is Adam (16) and I’v...       1

In [21]:
combined_df = pd.concat([df1, df2], ignore_index=True)

In [22]:
combined_df = combined_df.sample(frac=1).reset_index(drop=True)

In [23]:
combined_df.head()

                                                text  target
0  I'm almost at a breaking point...New Year's Ev...       1
1  There’s no joy leftI spent too much of my life...       1
2  I often cut myself. But of sanity not sadnessI...       1
3  Please just someone talk to meI'm crying and o...       1
4  Little do my friends know that they are the on...       0

In [24]:
combined_df.shape

(239805, 2)

In [25]:
combined_df.to_csv("mindlens_text_dataset.csv", index=False)